credentials:
  usernames:
    kelly:
      name: Kelly Graham
      email: kgraham@pjilaw.com
      password: "$2b$12$yUaFcwT4hfHqpC7jL22j0ODcjNNL/QzKk.aREH38B79.U7AmTbXqq"

cookie:
  name: referrals_app_auth
  key: "JOxrdDOKWN0y63OVm817ECvgYNMPJwcN"
  expiry_days: 30

preauthorized:
  emails:
    - kgraham@pjilaw.com
